<a href="https://www.kaggle.com/code/devendrarajpurohit58/types-of-probability?scriptVersionId=309834117" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [2]:
df_1=pd.read_csv(r'/kaggle/input/competitions/titanic/train.csv')
df_2=pd.read_csv(r'/kaggle/input/competitions/titanic/test.csv')

In [3]:
df=pd.concat([df_1,df_2])

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [5]:
#This represents the Joint Probability
pd.crosstab(df['Survived'],df['Pclass'],normalize='all')

Pclass           1         2         3
Survived
0.0       0.089787  0.108866  0.417508
1.0       0.152637  0.097643  0.133558

In [6]:
#This represents the Marginal Probability
pd.crosstab(df['Survived'],df['Pclass'],normalize='all',margins=True)

Pclass           1         2         3       All
Survived
0.0       0.089787  0.108866  0.417508  0.616162
1.0       0.152637  0.097643  0.133558  0.383838
All       0.242424  0.206510  0.551066  1.000000

In [7]:
# Understanding and implementing conditional probability
# Coinditional Probability is the probability of an event occuring given other event has already occured

pd.crosstab(df['Survived'],df['Pclass'],normalize='columns')
#Above code gives the conditional probability of survival provided they are in a given Pclass

Pclass          1         2         3
Survived
0.0       0.37037  0.527174  0.757637
1.0       0.62963  0.472826  0.242363

In [8]:
'''
Below code line is just the opposite of the previous cell code.
Which means now the already occured event is being in pclass and the next event is survival.
This code gives us the probability of a death/survival for particular pclass
'''
pd.crosstab(df['Survived'],df['Pclass'],normalize='index')

Pclass           1         2         3
Survived
0.0       0.145719  0.176685  0.677596
1.0       0.397661  0.254386  0.347953